Product overview
Captain-Crunch-Brigade/capstone pull request #12
Opened 2022-10-18 23:56 UTC by robertvgarcia

2022-10-18 23:59 UTC, Flaws77 approved these changes
Seems fine to me

2022-10-19 00:06 UTC, merged

2022-10-19 00:07 UTC, keewook2 requested changes

2022-10-19 00:07 UTC, keewook2 commented on client/src/components/ProductOverview/ImageGallery.jsx
> +  console.log(styleInfo)
remove console.log please

2022-10-19 00:07 UTC, keewook2 commented on client/src/components/ProductOverview/ProductInfo.jsx
> +        <span>&#9733;&#9733;&#9733;&#9733;&#9733; </span>
Better use Star components to show average star ratings!, and if hardcode is needed, you can copy and paste star unicode directly.

2022-10-19 00:07 UTC, keewook2 commented on client/src/components/ProductOverview/ProductInfo.jsx
> +        <a href="#"><small>Read all reviews</small></a>
Using <Link> in react-router-dom is recommended becuase if you use <a> tag it'll lose state and show lower performance.

2022-10-19 00:07 UTC, keewook2 commented on client/src/components/ProductOverview/ProductInfo.jsx
> +        <a href="#"><small>Read all reviews</small></a>
`<a>` tag